using System;
using System.Collections.Generic;
using System.Text;
using UnityEngine;

namespace TDPG.Generators.Seed
{
    /// <summary>
    /// Acts as the central factory and registry for all seeds within a specific game session or save file.
    /// Uses an "Evolving State" pattern.
    /// <br/>
    /// The GlobalSeed holds the "Master Entropy" and generates deterministic children (SubSeeds) 
    /// based on string keys, ensuring that the same save file always produces the same world.
    /// <br/>Every time a SubSeed is generated, the Master Base evolves, ensuring that 
    /// subsequent requests (even with the same key) result in distinct, high-entropy seeds.
    /// </summary>
    [Serializable]
    public class GlobalSeed:ISeed
    {
        /// <summary>
        /// The current internal entropy state. This value changes every time 
        /// <see cref="NextSubSeed"/> is called to ensure sequence uniqueness.
        /// </summary>
        public ulong Base { get; private set; }
        
        /// <summary>
        /// The identifier for this session (e.g., "SaveGame_01", "DailyRun_2025").
        /// </summary>
        public string Name { get; private set; }
        
        /// <summary>
        /// Optional description or metadata for the session.
        /// </summary>
        public string Description { get; private set; }

        /// <summary>
        /// Registry of all child seeds generated by this manager.
        /// </summary>
        [SerializeField]
        private List<Seed> subSeeds;
        
        /// <summary>
        /// Internal counter to assign unique IDs to new SubSeeds.
        /// </summary>
        [SerializeField]
        private int currIndex;

        /// <summary>
        /// Initializes a new Global Seed Manager.
        /// </summary>
        /// <param name="baseSeed">The master entropy value.</param>
        /// <param name="name">Session identifier.</param>
        /// <param name="description">Session description.</param>
        public GlobalSeed(ulong baseSeed, string name = null, string description = null)
        {
            Base = baseSeed;
            Name = name;
            Description = description;
            subSeeds = new List<Seed>();
            currIndex = 0;
        }

        /// <summary>
        /// Retrieves the Master Entropy value.
        /// </summary>
        public ulong GetBaseValue()
        {
            return Base;
        }

        public string GetName()
        {
            return Name;
        }
        
        [Serializable]
        private class SerializableGlobalSeed
        {
            public ulong @base;
            public string @name;
            public string @description;
            public List<Seed> @subSeeds;
            public int @currIndex;
        }

        /// <summary>
        /// Retrieves an existing SubSeed by its unique internal ID.
        /// </summary>
        /// <param name="id">The index of the seed in the registry.</param>
        /// <returns>The stored Seed instance.</returns>
        public Seed GetSubSeed(int id)
        {
            return subSeeds[id];
        }

        /// <summary>
        /// Generates a unique SubSeed using a 4-step Pipeline:
        /// <list type="number">
        /// <item>Combine Key + Counter and Scramble (Input Prep).</item>
        /// <item>Scramble the current Global Base (State Prep).</item>
        /// <item>Perform Genetic Crossover between Key and State (Breeding).</item>
        /// <item>Evolve the Global Base using the new Offspring (State Split).</item>
        /// </list>
        /// </summary>
        /// <param name="key">A context string (e.g. "Loot_Chest").</param>
        /// <returns>A deterministic but high-entropy SubSeed.</returns>
        public Seed NextSubSeed(string key)
        {
            //Update counter
            currIndex++;
            
            // Step 1: Input Prep (Hash + Scramble)
            ulong keyRaw = Genetic.GetDeterministicHash(key) ^ (uint)currIndex;
            ulong keyScrambled = Genetic.Scramble(keyRaw);
            
            // Step 2: State Prep (Scramble the Base so the 'gentle' crossover has high entropy)
            ulong stateScrambled = Genetic.Scramble(Base);
         
            // Step 3: Genetic Crossover
            byte[] parentA = BitConverter.GetBytes(stateScrambled);
            byte[] parentB = BitConverter.GetBytes(keyScrambled);
            ulong offspringValue = Genetic.ByteCrossover(parentA, parentB);
            
            // Step 4: State Evolution (The Split)
            // This ensures that even if you call "Card" and then "Card" again, 
            // the second "Card" starts with a different base.
            Base = Genetic.Scramble(Base ^ offspringValue);
            
            Seed newSeed = new Seed(offspringValue, currIndex, "CHILD_OF_GLOBAL_SEED", true);
            subSeeds.Add(newSeed);
            return newSeed;
        }

        /// <summary>
        /// Generates a unique fingerprint hash of the current object state.
        /// <br/>
        /// Useful for validating save file integrity or checking if the seed registry has changed.
        /// </summary>
        public string ToShortHash()
        {
            string importantData = $"{Name}{Base}{Description}{subSeeds?.Count ?? 0}";
            var hash = new Hash128();
            hash.Append(importantData);
            return hash.ToString();
        }

        /// <summary>
        /// Serializes the entire GlobalSeed state (including registry) to a JSON string.
        /// </summary>
        /// <returns>JSON representation of the object.</returns>
        public string Serialize()
        {
            var serializableData = new SerializableGlobalSeed
            {
                @base = GetBaseValue(),
                @name = Name,
                @description = Description,
                @subSeeds = subSeeds,
                @currIndex = currIndex
            };
            
            return JsonUtility.ToJson(serializableData, false); 
        }
        
        /// <summary>
        /// Reconstructs a GlobalSeed object from a JSON string.
        /// </summary>
        /// <param name="serializedData">The JSON string created by <see cref="Serialize"/>.</param>
        /// <returns>A restored GlobalSeed instance, or null if deserialization failed.</returns>
        public static GlobalSeed Deserialize(string serializedData)
        {
            try
            {
                var data = JsonUtility.FromJson<SerializableGlobalSeed>(serializedData);
                
                var globalSeed = new GlobalSeed(data.@base, data.@name, data.@description);

                if (data.@subSeeds != null)
                {
                    globalSeed.subSeeds = data.@subSeeds;
                    globalSeed.currIndex = data.@currIndex;
                }
                
                return globalSeed;
            }
            catch (Exception ex)
            {
                Debug.LogError($"Failed to deserialize GlobalSeed: {ex.Message}");
                return null;
            }
        }

    }
}