using UnityEngine;

namespace TDPG.Generators.Seed
{
    /// <summary>
    /// A MonoBehaviour wrapper that acts as the entry point for the TDPG Seed System in a Unity Scene.
    /// <br/>
    /// It initializes a <see cref="GlobalSeed"/> on Awake and serves as a simple factory for sub-seeds.
    /// </summary>
    public class GlobalSeedGameObject : MonoBehaviour
    {
        [Tooltip("The initial 64-bit master entropy value. Changing this changes everything generated by this object.")]
        [SerializeField] private ulong initVal;

        private GlobalSeed _globalSeed;
        private int _seedsCreated = 0;

        private void Awake()
        {
            _globalSeed = new GlobalSeed(initVal);    
        }

        /// <summary>
        /// Generates the next sequential sub-seed using a fixed debug key.
        /// <br/>
        /// <b>Note:</b> Since the key is hardcoded, the randomness is determined solely by the call order.
        /// Calling this 5 times will always produce the same 5 seeds in the same order.
        /// </summary>
        /// <returns>A new <see cref="Seed"/> instance derived from the global base.</returns>
        public Seed GetNextSeed()
        {
            _seedsCreated++;
            return _globalSeed.NextSubSeed("DebugKey_WillResultInDeterminism");
        }

        /// <summary>
        /// Retrieves a previously generated seed from the internal registry by its ID.
        /// </summary>
        /// <param name="id">The index of the seed (0 to TotalCreated).</param>
        /// <returns>The stored Seed object, or null if the ID is invalid.</returns>
        public Seed RetrieveSeed(int id)
        {
            if (id < 0 || id > _seedsCreated)
            {
                return null;
            }
            return _globalSeed.GetSubSeed(id);
        }
    }
}